import type { Metadata } from "next";
import "./styles/globals.css";
import { AuthProvider } from "./hooks/useAuth"; 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Aquí envolvemos la aplicación con AuthProvider */}
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
