// app/layout.tsx
import React from 'react';
import '../styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <div>Re-Loved</div>
          <nav>
            <a href="/">Inicio</a>
            <a href="/signin">Iniciar sesión</a>
            <a href="/signup">Registrarse</a>
          </nav>
        </header>
        <main>{children}</main>
        <footer>© {new Date().getFullYear()}</footer>
      </body>
    </html>
  );
}