name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-tests:
    name: Run Frontend Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x, 20.x, 21.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies (Frontend)
      working-directory: ./front
      run: npm install
    - name: Run tests (Frontend)
      working-directory: ./front
      run: npm test

  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x, 20.x, 21.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies (Backend)
      working-directory: ./back-end
      run: npm install
    - name: Set environment variables for backend
      run: |
        echo "JWT_SECRET=mysecret" >> $GITHUB_ENV
        echo "JWT_EXPIRATION=3600" >> $GITHUB_ENV
    - name: Run tests (Backend)
      working-directory: ./back-end
      run: npm test
